apiVersion: v1
kind: Service
metadata:
  name: frontend-{{ .Release.Namespace }}
  labels:
    {{- include "asbpfe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    {{- include "asbpfe.selectorLabels" . | nindent 4 }}
